---
- hosts: all
  gather_facts: False
  vars_files:
    - ../vars/auth
    - ../vars/machines
    - ../vars/zone
  tasks:
    - name: Delete the first instance
      gcp_compute_instance:
        name: "{{ name_zonea }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: "{{ auth_kind }}"
        state: absent
    - name: Delete the first address
      gcp_compute_address:
        name: "{{ name_zonea }}-ip"
        region: "{{ region }}"
        project: "{{ project }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: "{{ auth_kind }}"
        state: absent
