- name: Create main directory
  file:
    path: /home/ubuntu/main
    state: directory

- name: Create temp directory
  file:
    path: /home/ubuntu/temp
    mode: 777
    state: directory

- name: Update ubuntu
  shell: apt-get update

- name: Install python3 pip
  shell: echo y | sudo apt-get install python3-pip

- name: Install flask
  shell: 'pip3 install flask'

- name: Clone the cortex repo
  git:
    repo: git clone '{{ cortex_repo_url }}'
    dest: /home/ubuntu/temp
