- name: Check if repo cloned
  stat:
    path: "{{ research_dir }}"
  register: is_cloned
- name: Clone tensorflow repo
  shell: git clone "{{ tensorflow_repo }}"
  when: is_cloned.stat.exists == False
  args:
    chdir: "{{ home_dir }}"
- name: Protobuf compilation
  shell: protoc object_detection/protos/*.proto --python_out=.
  args:
    chdir: "{{ research_dir }}"
- name: Setting up environment var
  shell: "export PYTHONPATH={{ python_path }}"
  register: env_setting
  args:
    chdir: "{{ research_dir }}"
- name: Testing installation
  shell: python object_detection/builders/model_builder_test.py
  register: install_test
  args:
    chdir: "{{ research_dir }}"
- name: Validate install
  debug:
    msg: "{{ install_test.stderr_lines[-1] }}"
