---
- hosts: all
  become: true
  vars_files:
    - ../vars/external_vars.yml
  tasks:
    - name: Update system
      shell: apt-get update
    - name: Create app directory
      file:
        path: ~/app
        state: directory
    - name: Create server directory
      file:
        path: ~/app/server
        state: directory
    - name: Create temporary build directory
      file:
        path: ~/app/temp
        state: directory
      register: tempdir
    - name: Install python3
      shell: apt install python3
    - name: Install python3-pip
      shell: echo y | apt install python3-pip
    - name: upload requirements
      copy:
        src: ../static/requirements.txt
        dest: ~/app/temp/requirements.txt
