---
# Setup the system 
- name: Create an instance
  hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - ../gce_vars/auth
    - ../gce_vars/zone
  tasks:
    - name: Update the system
      shell: sudo apt-get update
    - name: Get path of root directory
      shell: pwd
      register: root_dir
    - set_fact:
        root_dir = "{{ root_dir.stdout }}"
    - name: Install python pip3
      shell: apt -y install python3-pip
    - name: Install python pip
      shell: apt -y install python-pip
    - name: Install libraries
      shell: apt-get -y install protobuf-compiler python-pil python-lxml python-tk
    - name: Install upgrade tools
      shell: pip install --upgrade setuptools
    - name: Upgrade pip
      shell: pip install --upgrade pip
    - name: Install tensorflow
      shell: pip install tensorflow
    - name: Install matplotlib
      shell: pip install matplotlib
    - name: Install few more libraries
      shell: "pip install --user {{ item }}"
      loop:
        - "Cython"
        - "contextlib2"
        - "pillow"
        - "lxml"
        - "jupyter"
        - "matplotlib"

