RESIZE = 0.5
IMAGE_WIDTH = 96 #int(600 * RESIZE)
IMAGE_HEIGHT = 96 #int(400 * RESIZE)
IMAGE_CHANNEL = 3
LATENT_DIM = 24
BATCH_SIZE = 32
ACTION_SPACE = 3
IMAGE_PIXELS = IMAGE_HEIGHT * IMAGE_WIDTH * IMAGE_CHANNEL
ST_SHAPES = [None, IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNEL]
AT_SHAPES = [None, ACTION_SPACE]
PI_SHAPES = [None, LATENT_DIM]
ADV_SHAPES = [None, 1]
ST_SHAPE = (-1, IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNEL)
ST_LT_SHAPES = [None, LATENT_DIM]
ST_LT_SHAPE = [-1, LATENT_DIM]

MAX_EP_STEP = 200

LOG = "tensorboard/"
MODEL_PATH ="saved/"
